version: 0.0
os: linux
files:
  - source: /home/subbu/services/
    destination: /home/subbu/services/apps
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 3600
      runas: root
    - location: scripts/start_server
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

